# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  author-service:
    image: author-service
    build:
      context: .
      dockerfile: ./Dockerfile
networks:
  microservice-net-postgresql:
    external: true
